# Generated by Django 5.1.7 on 2025-03-07 13:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id", models.IntegerField()),
                ("url", models.URLField(blank=True, default=None, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Loanplus", "Loanplus"),
                            ("SgroshiCPA2", "SgroshiCPA2"),
                            ("Novikredyty", "Novikredyty"),
                            ("TurboGroshi", "TurboGroshi"),
                            ("Crypsee", "Crypsee"),
                            ("Suncredit", "Suncredit"),
                            ("Lehko", "Lehko"),
                            ("Monto", "Monto"),
                            ("Limon", "Limon"),
                            ("Amigo", "Amigo"),
                            ("FirstCredit", "FirstCredit"),
                            ("Finsfera", "Finsfera"),
                            ("Pango", "Pango"),
                            ("Treba", "Treba"),
                            ("StarFin", "StarFin"),
                            ("BitCapital", "BitCapital"),
                            ("SgroshiCPL", "SgroshiCPL"),
                            ("LoviLave", "LoviLave"),
                            ("Prostocredit", "Prostocredit"),
                            ("Sloncredit", "Sloncredit"),
                            ("Clickcredit", "Clickcredit"),
                            ("Credos", "Credos"),
                            ("Dodam", "Dodam"),
                            ("SelfieCredit", "SelfieCredit"),
                            ("Egroshi", "Egroshi"),
                            ("Alexcredit", "Alexcredit"),
                            ("SgroshiCPA1", "SgroshiCPA1"),
                            ("Tengo", "Tengo"),
                            ("Credit7", "Credit7"),
                            ("Tpozyka", "Tpozyka"),
                            ("Creditkasa", "Creditkasa"),
                            ("Moneyveo", "Moneyveo"),
                            ("My Credit", "My Credit"),
                            ("Credit Plus", "Credit Plus"),
                            ("Miloan", "Miloan"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("sum_to", models.CharField(blank=True, default=None, null=True)),
                ("term_to", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "percent_rate",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferWall",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, default=None, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OfferWallOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wall_assignments",
                        to="admin_panel.offer",
                    ),
                ),
                (
                    "offer_wall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_assignments",
                        to="admin_panel.offerwall",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("offer_wall", "offer")},
            },
        ),
    ]
